version: "3.8"

services:

  php:
    build:
      context: ./docker/php
    ports:
      - "81:80"
    volumes:
      - ./src:/var/www/html
    networks:
      - default
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:10.5.5
    ports:
      - "3306:3306"
    volumes:
      - ./docker/volumes/mariadb:/var/lib/mysql
    networks:
      - default
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: RoboticsWorld
      MYSQL_USER: test_user
      MYSQL_PASSWORD: test_pass

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    networks:
      - default
    depends_on:
      - mariadb
    environment:
      PMA_HOST: mariadb
      PMA_USER: test_user
      PMA_PASSWORD: test_pass

networks:
  default:
    driver: bridge
